# Which analytes are aligned to an external chemical identifier?
# Exercises: skos:exactMatch to ChEBI; censo:casNumber

PREFIX censo: <https://w3id.org/censo/>
PREFIX cereg: <https://w3id.org/censo/reg/>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX geo:   <http://www.opengis.net/ont/geosparql#>

SELECT (COUNT(DISTINCT ?a) AS ?withChebi) WHERE {
  ?a a censo:Analyte ; skos:exactMatch ?x .
}
