#!/usr/bin/env python3
"""
Assess competitor ontologies whose FILES are not published, from their papers.

WHY A SEPARATE SCRIPT
---------------------
`07_verify_gap_table.py` decides each cell by parsing the ontology itself. That
is the strong form of evidence and it is what the gap table should rest on.

But the two closest competitors -- WaWO+ (Oliva-Felipe et al. 2017) and OPO
(Wang et al. 2020) -- do not publish a dereferenceable ontology file. Neither
paper carries a download URL for its own vocabulary. Leaving both as "?" would
be honest but would also leave the novelty claim untested against exactly the
work a reviewer will ask about.

So they are assessed from the full text, and the result is labelled as a
DIFFERENT AND WEAKER evidence class. A paper may describe an ontology that
contains a concept without naming it in prose; absence in the text is strong
evidence, not proof. Every count below is reproducible from the PDFs in refs/.

Inputs  : refs/papers/*.pdf
Outputs : eval/competitor_papers.md

Usage:  python scripts/11_assess_competitor_papers.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAPERS = ROOT / "refs" / "papers"
EVAL = ROOT / "eval"

try:
    from pypdf import PdfReader
except ImportError:
    try:
        from PyPDF2 import PdfReader
    except ImportError:
        sys.exit("pypdf is required:  pip install pypdf")

TARGETS = [
    ("WaWO+", "OlivaFelipe2017_WaWOplus.pdf",
     "Oliva-Felipe et al. 2017, Environ. Model. Softw. 89:106-119"),
    ("OPO", "Wang2020_OPO.pdf",
     "Wang et al. 2020, Water 12(3):715"),
    ("Jajaga expert system", "Jajaga2015_ExpertSystem.pdf",
     "Jajaga, Ahmedi & Ahmedi 2015, MTSR, CCIS 544:89-100"),
    ("Ahmedi river WQ", "Ahmedi2016_RiverWaterQuality.pdf",
     "Ahmedi et al. 2016, Procedia Computer Science"),
    ("Acquirium", "Acquirium2025_WaterTreatment.pdf",
     "Saka et al., water-treatment data interoperability (ACM)"),
]

# Same concept families as the file-based check, so the two tables are comparable.
CONCEPTS = {
    "detection limit": [r"detection limit", r"limit of detection", r"\bLOD\b",
                        r"limit of quantifi", r"\bLOQ\b", r"reporting limit"],
    "censoring": [r"censor", r"non[- ]?detect", r"nondetect", r"not detected",
                  r"below the (detection )?limit", r"left[- ]censor"],
    "undecidable outcome": [r"undecid", r"indetermin", r"undetermin",
                            r"not assessable", r"inconclusive",
                            r"cannot be determined"],
    "regulatory threshold": [r"\bEQS\b", r"quality standard", r"threshold",
                             r"limit value", r"exceedance", r"Water Framework"],
    "interval-valued result": [r"lower bound", r"upper bound",
                               r"interval[- ]valued", r"range of values"],
    "rule layer": [r"\bSWRL\b", r"\bSHACL\b", r"\bSPIN\b", r"rule[s]? engine"],
    "land use / pressures": [r"land[- ]use", r"land cover", r"pressure[s]?\b",
                             r"point source", r"diffuse source"],
    "published ontology file": [r"available (at|from)\s+http",
                                r"can be downloaded", r"\.owl\b", r"\.ttl\b",
                                r"github\.com", r"purl\.org", r"w3id\.org"],
}
COMPILED = {k: [re.compile(p, re.I) for p in v] for k, v in CONCEPTS.items()}


def read_pdf(path: Path) -> str:
    r = PdfReader(path)
    out = []
    for p in r.pages:
        try:
            out.append(p.extract_text() or "")
        except Exception:
            continue
    # repair line-break hyphenation so "detec- tion limit" is still found
    text = "\n".join(out)
    text = re.sub(r"(\w)[-­]\s*\n\s*(\w)", r"\1\2", text)
    text = re.sub(r"\s+", " ", text)
    return text


def context(text: str, pattern: re.Pattern, width: int = 90):
    m = pattern.search(text)
    if not m:
        return ""
    a = max(0, m.start() - width // 2)
    return text[a:a + width].strip()


def main() -> int:
    EVAL.mkdir(parents=True, exist_ok=True)
    results = []
    for label, fname, cite in TARGETS:
        path = PAPERS / fname
        if not path.exists():
            results.append((label, cite, None, {}, 0))
            continue
        text = read_pdf(path)
        found = {}
        for concept, pats in COMPILED.items():
            hits = []
            for p in pats:
                n = len(p.findall(text))
                if n:
                    hits.append((p.pattern, n, context(text, p)))
            found[concept] = hits
        results.append((label, cite, path, found, len(text)))

    order = list(CONCEPTS)

    L = []
    A = L.append
    A("# Competitor ontologies assessed from their papers\n")
    A("Generated by `scripts/11_assess_competitor_papers.py`.\n")
    A("> **Evidence class: WEAKER than the file-based check.** "
      "`eval/gap_table.md` decides each cell by parsing the ontology itself. "
      "Neither WaWO+ nor OPO publishes a dereferenceable ontology file — no "
      "download URL for the vocabulary appears in either paper — so they are "
      "assessed from the full text instead. A paper can describe an ontology "
      "that contains a concept without naming it in prose, so absence here is "
      "strong evidence, not proof. The two tables must not be merged without "
      "this distinction.\n")

    A("## Concept coverage\n")
    A("| concept | " + " | ".join(l for l, _, _, _, _ in results) + " |")
    A("|---" * (len(results) + 1) + "|")
    for c in order:
        cells = []
        for _, _, path, found, _ in results:
            if path is None:
                cells.append("?")
            else:
                n = sum(n for _, n, _ in found.get(c, []))
                cells.append(f"**{n}**" if n else "—")
        A(f"| {c} | " + " | ".join(cells) + " |")
    A("")
    A("Cells are occurrence counts of the concept's search terms in the full "
      "text; `—` means zero occurrences.\n")

    A("## What this establishes\n")
    for label, cite, path, found, nchars in results:
        if path is None:
            A(f"### {label}\n- paper not available\n")
            continue
        dl = sum(n for _, n, _ in found.get("detection limit", []))
        cen = sum(n for _, n, _ in found.get("censoring", []))
        und = sum(n for _, n, _ in found.get("undecidable outcome", []))
        A(f"### {label} — {cite}\n")
        A(f"- full text scanned: {nchars:,} characters")
        A(f"- **detection limit / LOD / LOQ: {dl} occurrences**")
        A(f"- **censoring / non-detection: {cen} occurrences**")
        A(f"- **undecidable outcome: {und} occurrences**")
        for c in ("regulatory threshold", "rule layer", "land use / pressures"):
            hits = found.get(c, [])
            if hits:
                ex = hits[0][2]
                A(f"- {c}: {sum(n for _, n, _ in hits)} occurrences — "
                  f"e.g. \"…{ex}…\"")
        A("")

    A("## Conclusion for the gap table\n")
    # These counts were hardcoded as "four" and stayed there when a fifth paper
    # (Acquirium) was added: the table above listed five columns while the prose
    # below said four, and the manuscript said five. Derived from the data now.
    scanned = [r for r in results if r[2] is not None]
    n_scanned = len(scanned)
    n_thr = sum(1 for r in scanned
                if sum(n for _, n, _ in r[3].get("regulatory threshold", [])))
    n_rules = sum(1 for r in scanned
                  if sum(n for _, n, _ in r[3].get("rule layer", [])))
    WORD = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six",
            7: "seven", 8: "eight"}
    w = WORD.get(n_scanned, str(n_scanned))
    A(f"Across {w} papers, all squarely about ontologies for river water "
      "quality, the terms *detection limit*, *LOD*, *LOQ*, *censoring* and "
      f"*non-detection* do not appear once. "
      + ("All " + w if n_thr == n_scanned
         else f"{WORD.get(n_thr, n_thr).capitalize()} of the {w}")
      + " model regulatory thresholds and "
      + f"{WORD.get(n_rules, n_rules)} carry a SWRL rule layer, "
      "so neither thresholds nor rules are claimed as novel here.\n")
    A("**This must be read together with WHOW.** The Water Health Open "
      "Knowledge Graph (`https://w3id.org/whow/onto/water-monitoring`) does "
      "publish its ontology, and it *does* represent a below-limit result as a "
      "value range -- its own comment gives `<10` meaning `[0, 10]`. WHOW is "
      "the closest prior work and this project extends it.\n")
    A("The defensible claim is therefore about the interval's PROVENANCE, not "
      "the interval:\n")
    A("> Existing water-quality ontologies either ignore censoring entirely "
      f"(the {w} assessed here) or record the resulting interval anonymously "
      "(WHOW). None binds the interval to the detection limit that produced "
      "it, distinguishes a censored result from a merely imprecise one, or "
      "admits an undecidable compliance outcome. Where a detection limit "
      "exists at all (SSN's Systems module) it describes the **sensor**, not "
      "the **measurement**.\n")

    text = "\n".join(L)
    (EVAL / "competitor_papers.md").write_text(text, encoding="utf-8")
    print(text)
    print(f"\nwrote: {EVAL/'competitor_papers.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
