#!/usr/bin/env python3
"""
Run the FOOPS! FAIR assessment against the PUBLISHED ontology and write the
result up.

WHY THIS EXISTS
---------------
OOPS! checks modelling pitfalls; FOOPS! checks whether the ontology is
findable, accessible, interoperable and reusable as published. The manuscript
used to report FOOPS! as "not yet run", which is honest but is exactly the gap
a semantic-web referee asks about. It costs one HTTP call to close.

WHAT IS ASSESSED
----------------
The PUBLISHED IRI, https://w3id.org/censo/ -- not the local file. That is the
point of the tool: it tests content negotiation, version IRI resolution and
registry presence, none of which a file on disk can exhibit. FOOPS! fetches the
IRI itself, so nothing is uploaded.

THE NETWORK, AND WHY THE PIPELINE STAYS DETERMINISTIC
-----------------------------------------------------
Every other stage runs offline. This one cannot, so the raw response is cached
in eval/foops_raw.json and committed. With no network -- or with --cached --
the script re-reads the cache and writes the same report, so `00_run_all.py`
never fails for want of a connection and the reported score cannot drift
silently between runs. Re-running with a connection overwrites the cache, and
the report carries the date the assessment was retrieved.

Inputs  : https://w3id.org/censo/  (or eval/foops_raw.json)
Outputs : eval/foops_assessment.md
          eval/foops_raw.json

Usage:  python scripts/15_foops.py [--cached]
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.error
import urllib.request
from collections import defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EVAL = ROOT / "eval"
RAW = EVAL / "foops_raw.json"
OUT = EVAL / "foops_assessment.md"

ENDPOINT = "https://foops.linkeddata.es/assessOntology"
ONTOLOGY = "https://w3id.org/censo/"
TIMEOUT = 300           # the service parses and dereferences; it is not fast

CATEGORIES = ("Findable", "Accessible", "Interoperable", "Reusable")


def fetch() -> dict:
    body = json.dumps({"ontologyUri": ONTOLOGY}).encode("utf-8")
    req = urllib.request.Request(
        ENDPOINT, data=body,
        headers={"Content-Type": "application/json",
                 "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=TIMEOUT) as r:
        return json.loads(r.read().decode("utf-8"))


def load_cached() -> dict:
    if not RAW.exists():
        sys.exit(f"no cached response at {RAW} and none could be fetched")
    return json.loads(RAW.read_text(encoding="utf-8"))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cached", action="store_true",
                    help="do not call the service; use eval/foops_raw.json")
    args = ap.parse_args()

    retrieved = None
    if args.cached:
        data = load_cached()
    else:
        try:
            data = fetch()
            RAW.write_text(json.dumps(data, indent=1, ensure_ascii=False),
                           encoding="utf-8")
            retrieved = date.today().isoformat()
        except (urllib.error.URLError, TimeoutError, OSError) as e:
            print(f"  FOOPS! unreachable ({e}); falling back to the cache")
            data = load_cached()

    checks = data.get("checks", [])
    if not checks:
        sys.exit("the response carried no checks")

    # FOOPS! reports a weighted overall score and a per-check pass/fail; the
    # per-category counts below are ours, and are counts of checks, not of the
    # weights behind the overall score. Saying so stops the two being read as
    # the same quantity.
    overall = float(data.get("overall_score", 0.0))
    by_cat = defaultdict(list)
    for c in checks:
        by_cat[c.get("category_id", "?")].append(c)

    passed = [c for c in checks if c.get("status") == "ok"]
    failed = [c for c in checks if c.get("status") != "ok"]

    A = []
    add = A.append
    add("# FAIR assessment of the published ontology (FOOPS!)\n")
    add(f"Generated by `scripts/15_foops.py` against `{ONTOLOGY}` — the "
        "published IRI, not the local file, because content negotiation, "
        "version-IRI resolution and registry presence are properties of the "
        "publication and not of the serialisation.\n")
    if retrieved:
        add(f"- retrieved: **{retrieved}**")
    else:
        add("- retrieved: **from the cached response** "
            "(`eval/foops_raw.json`)")
    add(f"- ontology title as read by the service: "
        f"**{data.get('ontology_title', '—')}**")
    add(f"- licence as read by the service: "
        f"**{data.get('ontology_license', '—')}**")
    add(f"- FOOPS! overall score: **{overall:.2f}**")
    add(f"- checks passed: **{len(passed)} of {len(checks)}**\n")

    add("## By FAIR category\n")
    add("Counts of checks. The overall score above is FOOPS!'s own weighting "
        "and is not the ratio of these counts.\n")
    add("| category | passed | run |")
    add("|---|---|---|")
    for cat in CATEGORIES:
        cs = by_cat.get(cat, [])
        ok = sum(1 for c in cs if c.get("status") == "ok")
        add(f"| {cat} | {ok} | {len(cs)} |")
    add("")

    if failed:
        add("## What does not pass, and why\n")
        add("| check | category | what the service reports |")
        add("|---|---|---|")
        for c in sorted(failed, key=lambda c: c.get("abbreviation", "")):
            exp = " ".join(str(c.get("explanation", "")).split())
            add(f"| `{c.get('abbreviation')}` | {c.get('category_id')} "
                f"| {exp} |")
        add("")

    add("## Reading\n")
    add("Two kinds of failure sit in the table above and they are not "
        "equivalent. **Missing annotations** — a citation, a publisher, an "
        "issue date, a DOI — are properties of the file and can be added "
        "without changing a single axiom. **Registry absence** is a property "
        "of the wider ecosystem: the ontology is not indexed in a public "
        "registry, which no edit to the file achieves and which is why the "
        "metadata-when-the-ontology-is-gone check fails with it.\n")
    add("Nothing in the assessment bears on the modelling claims of the "
        "paper. It is reported because a reader asked to reuse an ontology is "
        "entitled to know what reuse currently costs.\n")

    OUT.write_text("\n".join(A) + "\n", encoding="utf-8")
    print(f"  overall {overall:.2f}, {len(passed)}/{len(checks)} checks passed")
    print(f"  wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
