#!/usr/bin/env python3
"""How much of the annual-mean record the disaggregated release can reach.

WHY THIS IS MEASURED RATHER THAN DESCRIBED
------------------------------------------
A maximum allowable concentration applies to an individual measurement, not to
an annual mean, so assessing it needs the disaggregated release. That release is
the less complete of the two: sample-level reporting is not uniform across
Member States, and a share computed over the rows it happens to cover is a
statement about those rows and not about the record.

Section 3 therefore says how far it reaches, and "how far" has to be a number:
how many of the river station-years the aggregated release holds have any sample
behind them here, and how many samples a covered station-year typically has. The
median is reported rather than the mean because the distribution is heavily
skewed -- a handful of station-years carry hundreds of samples and most carry a
few -- and a mean would describe neither.

The existing coverage figure in eval/mac_exceedance.md answers a narrower
question: of the station-years for substances that HAVE a maximum-allowable
standard, how many can be read both ways. This one is about the release, not
about the assessment, so it is computed over every river station-year.

Inputs  : Data/waterbase/*Disaggregated*  (optional; the stage skips without it)
          Data/waterbase/*Aggregated*     (the station-years to cover)
Outputs : derived/processed/disaggregated_coverage.csv
          eval/disaggregated_coverage.md

Usage:  python scripts/27b_disaggregated_coverage.py
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "Data" / "waterbase"
PROC = ROOT / "derived" / "processed"
EVAL = ROOT / "eval"

sys.path.insert(0, str(Path(__file__).resolve().parent))
_mac = __import__("27_mac_exceedance")
_ext = __import__("22_waterbase_external")
stream_rows, find = _mac.stream_rows, _mac.find
open_rows, pick = _ext.open_rows, _ext.pick


def main() -> int:
    dis = find("disaggregated")
    agg = find("aggregated")
    if dis is None or agg is None:
        print("  ! aggregated or disaggregated release absent; skipping")
        return 0

    # ---- the river station-years the annual-mean record holds --------------
    it = open_rows(agg)
    head = next(it)
    col = pick(head)
    g = lambda r, k: (r[col[k]].strip() if k in col and col[k] < len(r) else "")
    keys = set()
    for r in it:
        if "category" in col and g(r, "category") not in ("RW", ""):
            continue
        y = g(r, "year")[:4]
        if g(r, "site") and g(r, "code") and y:
            keys.add((g(r, "site"), g(r, "code"), y))
    print(f"  {len(keys):,} river station-years in the aggregated release")

    # ---- how many of them any sample reaches -------------------------------
    rows = stream_rows(dis)
    dhead = next(rows)
    dcol = pick(dhead)
    dg = lambda r, k: (r[dcol[k]].strip()
                       if k in dcol and dcol[k] < len(r) else "")
    per = {}
    n_samples = n_river = 0
    for r in rows:
        n_samples += 1
        if "category" in dcol and dg(r, "category") not in ("RW", ""):
            continue
        n_river += 1
        y = dg(r, "year")[:4]
        k = (dg(r, "site"), dg(r, "code"), y)
        if k in keys:
            per[k] = per.get(k, 0) + 1

    covered = len(per)
    counts = sorted(per.values())
    med = counts[len(counts) // 2] if counts else 0
    q1 = counts[len(counts) // 4] if counts else 0
    q3 = counts[3 * len(counts) // 4] if counts else 0
    pct = 100 * covered / len(keys) if keys else 0.0

    PROC.mkdir(parents=True, exist_ok=True)
    with (PROC / "disaggregated_coverage.csv").open(
            "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["quantity", "value"])
        for k, v in (("aggregated_river_station_years", len(keys)),
                     ("disaggregated_rows_total", n_samples),
                     ("disaggregated_river_samples", n_river),
                     ("station_years_covered", covered),
                     ("coverage_pct", f"{pct:.2f}"),
                     ("samples_per_covered_p25", q1),
                     ("samples_per_covered_median", med),
                     ("samples_per_covered_p75", q3)):
            w.writerow([k, v])

    EVAL.mkdir(parents=True, exist_ok=True)
    (EVAL / "disaggregated_coverage.md").write_text("\n".join([
        "# How far the disaggregated release reaches\n",
        "Generated by `scripts/27b_disaggregated_coverage.py`.\n",
        "A maximum allowable concentration applies to an individual "
        "measurement, so assessing it needs sample-level data. Sample-level "
        "reporting is not uniform between Member States, so every "
        "maximum-allowable result in this paper describes the stratum below "
        "and not the record.\n",
        "| | |", "|---|---|",
        f"| river station-years in the aggregated release "
        f"| **{len(keys):,}** |",
        f"| river samples in the disaggregated release "
        f"| **{n_river:,}** |",
        f"| of those station-years reached by at least one sample "
        f"| **{covered:,}** ({pct:.1f} %) |",
        f"| samples per covered station-year, median | **{med}** "
        f"(quartiles {q1}–{q3}) |",
        "",
        "The median is reported rather than the mean because the "
        "distribution is skewed: a few station-years carry hundreds of "
        "samples and most carry a handful, so a mean would describe "
        "neither.\n",
    ]) + "\n", encoding="utf-8")
    print(f"  {covered:,} of {len(keys):,} station-years covered "
          f"({pct:.1f} %), median {med} samples")
    print("  wrote eval/disaggregated_coverage.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
