#!/usr/bin/env python3
"""Print the authoritative value of every quantity the manuscript states.

WHY THIS IS A SCRIPT

When a correction moves the data, every number in the prose has to be restated,
and the audit's near-match detector is the wrong tool for the job: it pairs an
asserted value with whatever recomputed value happens to be numerically near, so
after a large correction it reports "asserts 60898 where the data give 61034"
beside "asserts 60898 where the data give 59251" for two different quantities.
Repairing prose from those pairings introduces errors instead of removing them.

This reads the processed data and prints one labelled value per quantity, with
the section that states it. The label text matches scripts/99_audit.py, so a
value restated from here is a value that check_claim() will accept.

Usage:  python scripts/94_restate.py
Writes: eval/RESTATE.md
"""
from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROC = ROOT / "derived" / "processed"
EVAL = ROOT / "eval"


def load(name):
    p = PROC / name
    if not p.exists():
        return []
    with p.open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def main() -> int:
    EVAL.mkdir(parents=True, exist_ok=True)
    L = ["# Restatement table",
         "",
         "Generated by `scripts/94_restate.py` from `derived/processed/*.csv`.",
         "",
         "Every quantity the manuscript states, with its authoritative value.",
         "**Do not repair prose from the audit's near-match pairings** -- after a",
         "correction that moves many numbers, the detector pairs an asserted",
         "value with whatever recomputed value happens to be numerically near.",
         "Restate from this table instead.",
         ""]

    def row(section, label, value, note=""):
        v = (f"{value:,}" if isinstance(value, int)
             else f"{value:.1f}" if isinstance(value, float) else str(value))
        L.append(f"| {section} | {label} | **{v}** | {note} |")

    S = load("waterbase_summary.csv")
    tot = next((r for r in S if r["scope"] == "total"), None)
    L += ["## Section 5.1 -- the record", "",
          "| section | quantity | value | note |", "|---|---|---|---|"]
    if tot:
        n, smp = int(tot["n"]), max(int(tot["samples"]), 1)
        eq = max(int(tot["has_eqs"]), 1)
        row("5.1", "river station-years", n)
        row("5.1", "underlying samples", int(tot["samples"]))
        row("5.1", "samples below the quantification limit %",
            100 * int(tot["samples_below"]) / smp)
        row("5.1", "station-years declaring nothing", int(tot["silent"]))
        row("5.1", "declaring nothing %", 100 * int(tot["silent"]) / n)
        row("5.1", "station-years with a European standard", eq)
        row("5.1", "LOQ above the EQS", int(tot["loq_gt_eqs"]))
        row("5.1", "LOQ above the EQS %", 100 * int(tot["loq_gt_eqs"]) / eq)
        row("5.1", "failing the 30 % criterion %",
            100 * int(tot["loq_gt_30pct_eqs"]) / eq)
        # Both denominators, named apart. This row used to carry only the
        # second, under the first one's name -- see the note in
        # scripts/99_audit.py::check_remaining_claims. 5.1 asserts the share of
        # ALL station-years; the era table in 5.2 uses the share of CENSORED
        # ones. A restatement table that gives one number for two quantities is
        # worse than no restatement table, because it is trusted.
        row("5.1", "station-years substituting at source %",
            100 * int(tot["censored_with_value"]) / n,
            "of all river station-years -- the value 5.1 asserts")
        row("5.2", "censored rows carrying a positive value %",
            100 * int(tot["censored_with_value"]) / max(int(tot["censored"]), 1),
            "of censored station-years -- the era table's denominator")
        row("5.1", "substances", len(
            [r for r in S if r["scope"] == "substance"]))
        row("5.1", "reporting countries", len(
            [r for r in S if r["scope"] == "country"]))

    subs = [r for r in S if r["scope"] == "substance"]
    always = sorted(r["key"] for r in subs
                    if int(r["has_eqs"]) and
                    int(r["loq_gt_eqs"]) == int(r["has_eqs"]))
    row("5.1", "substances at 100 % LOQ-above-EQS",
        f"{len(always)}: {', '.join(always) or 'none'}")

    cls = {r["key"]: r for r in S if r["scope"] == "class"}
    for k, lbl in (("Metals", "metals"),
                   ("Organic micropollutants", "organics")):
        r = cls.get(k)
        if r and int(r["samples"]):
            row("6.1", f"{lbl}: below LOQ %",
                100 * int(r["samples_below"]) / int(r["samples"]))

    run = {r["key"]: int(r["n"]) for r in S if r["scope"] == "run_scope"}
    if run.get("pairs_multiyear"):
        m = run["pairs_multiyear"]
        row("5.3", "station-substance pairs in >1 year", m)
        row("5.3", "pairs with more than one limit %",
            100 * run["pairs_multi_limit"] / m)
        row("5.3", "pairs reporting any method code",
            run["pairs_with_any_method"])
        row("5.3", "pairs reporting any method code %",
            100 * run["pairs_with_any_method"] / m)
        row("5.3", "pairs with more than one method code",
            run["pairs_multi_method"])
        row("5.3", "pairs whose limit change crosses the standard",
            run["pairs_crossing_standard"])

    # the annual series
    yrs = {int(r["key"]): r for r in S if r["scope"] == "year"}
    if yrs:
        pct = lambda r, k, d: 100 * int(r[k]) / max(int(r[d]), 1)
        silent = {y: pct(r, "silent", "n") for y, r in yrs.items()}
        crit = {y: pct(r, "loq_gt_30pct_eqs", "has_eqs")
                for y, r in yrs.items() if int(r["has_eqs"])}
        over = {y: pct(r, "loq_gt_eqs", "has_eqs")
                for y, r in yrs.items() if int(r["has_eqs"])}
        plotted = sorted(y for y, r in yrs.items() if int(r["n"]) >= 20000)
        row("5.2", "years plotted in the annual figure", len(plotted))
        zf = next((y for y in plotted if silent[y] < 0.05
                   and all(silent[z] < 0.05 for z in plotted if z >= y)), None)
        if zf:
            prev = max(y for y in plotted if y < zf)
            row("5.2", "the year the omission stops", zf)
            row("5.2", "years it has held",
                sum(1 for y in plotted if y >= zf))
            row("5.2", "omission % the year before it stops", silent[prev])
            row("5.2", "omission % the year it stops", silent[zf])
        testable = sorted(y for y in plotted
                          if silent[y] < 50.0 and y in crit)
        if testable:
            a, b = testable[0], testable[-1]
            row("5.2", f"30 % criterion, {a}", crit[a])
            row("5.2", f"30 % criterion, {b}", crit[b])
            row("5.2", f"limit above the standard, {a}", over[a])
            row("5.2", f"limit above the standard, {b}", over[b])
        sv = [pct(yrs[y], "censored_with_value", "censored") for y in plotted
              if int(yrs[y]["censored"])]
        if sv:
            row("5.2", "substitution at source, lowest year", min(sv))
            row("5.2", "substitution at source, highest year", max(sv))

    era = {r["key"]: r for r in S if r["scope"] == "era"}
    for k, lbl in (("pre2015", "before 2015"), ("2015plus", "2015 onwards")):
        r = era.get(k)
        if not r:
            continue
        n = max(int(r["n"]), 1)
        eq = max(int(r["has_eqs"]), 1)
        row("5.2", f"{lbl}: station-years", int(r["n"]))
        row("5.2", f"{lbl}: declaring nothing %", 100 * int(r["silent"]) / n)
        row("5.2", f"{lbl}: LOQ above the EQS %",
            100 * int(r["loq_gt_eqs"]) / eq)
        row("5.2", f"{lbl}: failing the 30 % criterion %",
            100 * int(r["loq_gt_30pct_eqs"]) / eq)
        row("5.2", f"{lbl}: censored carrying a value %",
            100 * int(r["censored_with_value"]) / max(int(r["censored"]), 1))
    if era:
        row("5.2", "share of the record dated 2015 or later %",
            100 * int(era["2015plus"]["n"])
            / max(sum(int(r["n"]) for r in era.values()), 1))

    # the three-valued assessment over the population, subtyped by the reason
    V = load("waterbase_verdicts_population.csv")
    if V:
        n = defaultdict(int)
        for r in V:
            n[(r["substitution"], r["censo_outcome"],
               r["two_valued_outcome"])] += int(r["n"])
        outs = ("compliant", "exceedance", "possible_exceedance",
                "precondition_unmet", "method_insufficient",
                "indeterminate_unresolved", "indeterminate_other")
        totp = sum(v for (s, _, _), v in n.items() if s == "zero")
        row("5.4", "assessments in the graph", totp)
        exc = {k: sum(n[(k, o, "exceeding")] for o in outs)
               for k in ("zero", "half", "full")}
        for k in ("zero", "half", "full"):
            row("5.4", f"two-valued exceedances ({k})", exc[k])
        row("5.4", "substitution fold-change", exc["full"] / exc["zero"])
        real = n[("zero", "exceedance", "exceeding")]
        row("5.4", "exceedances the law can affirm", real)
        row("5.4", "created by the half-LOQ substitution",
            exc["half"] - exc["zero"])
        row("5.4", "created by the half-LOQ substitution %",
            100 * (exc["half"] - exc["zero"]) / exc["half"])
        row("5.4", "set aside: method limit exceeds the standard",
            n[("zero", "method_insufficient", "exceeding")])
        row("5.4", "set aside: interval straddles the standard",
            n[("zero", "possible_exceedance", "exceeding")])
        row("5.4", "quantified above the standard but set aside",
            n[("zero", "method_insufficient", "exceeding")]
            + n[("zero", "possible_exceedance", "exceeding")])
        row("5.4", "exceedances resting on an unresolved number",
            n[("zero", "indeterminate_unresolved", "exceeding")])
        parts = {
            "precondition unmet %": ("precondition_unmet",),
            "limit above the standard %": ("method_insufficient",),
            "no bound at all %": ("indeterminate_unresolved",
                                  "indeterminate_other"),
            "possible-exceedance %": ("possible_exceedance",),
        }
        shares = {}
        for lbl, os_ in parts.items():
            shares[lbl] = 100 * sum(n[("zero", o, t)] for o in os_
                                    for t in ("compliant", "exceeding")) / totp
            row("5.4", lbl, shares[lbl])
        row("5.4", "unsupportable %", sum(round(v, 1) for v in shares.values()))
        row("5.4", "PreconditionUnmet assessments",
            sum(n[("zero", "precondition_unmet", tt)]
                for tt in ("compliant", "exceeding")))
        row("5.4", "PossibleExceedance assessments",
            sum(n[("zero", "possible_exceedance", t)]
                for t in ("compliant", "exceeding")))

    D = load("dual_regulation.csv")
    if D:
        g = {r["key"]: int(r["n"]) for r in D if r["scope"] == "total"}
        for k in ("rows_scored", "rows_co_regulated", "co_regulated_differ"):
            if k in g:
                row("5.6", k.replace("_", " "), g[k])
        if g.get("rows_scored"):
            # the cross scope carries the two verdicts in their own columns,
            # not packed into the key
            changed = sum(int(r["n"]) for r in D if r["scope"] == "cross"
                          and r["eu_outcome"] != r["tr_outcome"])
            row("5.6", "changed outcome %", 100 * changed / g["rows_scored"])
        if g.get("rows_co_regulated"):
            row("5.6", "co-regulated divergence %",
                100 * g["co_regulated_differ"] / g["rows_co_regulated"])

    M = load("mac_exceedance.csv")
    if M:
        t_ = next((r for r in M if r["scope"] == "total"), None)
        if t_:
            n = max(int(t_["n"]), 1)
            row("5.7", "MAC: assessable samples", int(t_["n"]))
            row("5.7", "MAC: exceedances", int(t_["exceedance"]))
            row("5.7", "MAC: exceedance %", 100 * int(t_["exceedance"]) / n)
            row("5.7", "MAC: undecidable samples", int(t_["method_insufficient"]))
            row("5.7", "MAC: undecidable %",
                100 * int(t_["method_insufficient"]) / n)
        cross = {r["key"]: int(r["n"]) for r in M
                 if r["scope"] == "station_year_cross"}
        both = cross.get("both_assessable", 0)
        if both:
            row("5.7", "MAC: station-years assessable under both", both)
            diff = (cross.get("compliant_aa__exceeding_mac", 0)
                    + cross.get("exceeding_aa__compliant_mac", 0))
            row("5.7", "MAC: disagree either way %", 100 * diff / both)
            row("5.7", "MAC: compliant on the mean, exceeding on a sample",
                cross.get("compliant_aa__exceeding_mac", 0))
            row("5.7", "MAC: compliant on the mean, exceeding on a sample %",
                100 * cross.get("compliant_aa__exceeding_mac", 0) / both)

    C = load("country_confounders.csv")
    raw = [float(r["raw"]) for r in C if r.get("raw")]
    if raw:
        row("5.8", "country spread, lowest", min(raw))
        row("5.8", "country spread, highest", max(raw))

    L.append("")
    (EVAL / "RESTATE.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))
    print(f"\nwrote {EVAL / 'RESTATE.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
