#!/usr/bin/env python3
"""
Build a manifest linking every number in the manuscript to the artefact that
produced it, and flag any that cannot be traced.

WHY
---
A reviewer's fastest test of a reproducibility claim is to pick a number from
the abstract and ask where it came from. This script answers that mechanically:
it extracts every numeric literal from the LaTeX sources, checks whether the
same value occurs in a generated file under eval/ or derived/processed/, and
lists the ones that do not.

An untraceable number is not necessarily wrong -- it may be a page count or a
year -- but it must be justified deliberately rather than by omission. Known
non-data numbers are listed in ALLOWED and everything else must resolve.

Outputs: eval/numbers_manifest.md
Exit code 1 if any number in the text cannot be traced and is not allow-listed.

Usage:  python scripts/95_numbers_manifest.py
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAPER = ROOT / "paper"
EVAL = ROOT / "eval"
PROC = ROOT / "derived" / "processed"

# \num{...} is how the manuscript writes every data value (siunitx).
NUM = re.compile(r"\\num\{([0-9][0-9.,]*)\}")

# Numbers that legitimately have no data provenance.
ALLOWED = {
    "2017", "2018", "2026", "2016", "2008", "2013", "2024", "2020", "2015",
    "2012", "2023", "2022", "2011", "2007", "2006", "1", "2", "3", "4", "5",
    "10", "18",              # counts of sections, list items, ontologies
    "0.99",                  # calibration R2 threshold quoted from the source
    "4.0",                   # licence version
    # Cited from Lipinski (2026), not produced here. A number taken from a
    # reference must not be "traced" to one of our own outputs -- and two of
    # these (66.6, which matched a substring somewhere) were "tracing" to files
    # that have nothing to do with them, which is worse than an honest gap.
    "1259636", "66.6", "57.3", "36.1",
    # Wilkinson et al. (2022), cited in the introduction: a survey of 1052
    # sites on 258 rivers across 104 countries. Not ours, not shipped.
    "1052", "258", "104",
}

SOURCES = {
    # This script's OWN output is excluded. Including it makes the check
    # circular: numbers_manifest.md lists every value it just read out of the
    # manuscript, so every value trivially "traces" to it and the audit can
    # never fail. Several numbers were being certified this way.
    "eval": sorted(f for f in EVAL.glob("*.md")
                   if f.name != "numbers_manifest.md"),
    "processed": sorted(PROC.glob("*.csv")),
}


def load_haystacks():
    """Text of every generated artefact, keyed by a short label."""
    hay = {}
    for kind, files in SOURCES.items():
        for f in files:
            try:
                hay[f"{kind}/{f.name}"] = f.read_text(encoding="utf-8",
                                                      errors="replace")
            except Exception:
                continue
    return hay


def variants(tok: str):
    """A value may be written 76651, 76,651 or 76651.0 across artefacts."""
    plain = tok.replace(",", "")
    out = {tok, plain}
    if "." not in plain:
        try:
            out.add(f"{int(plain):,}")
        except ValueError:
            pass
    else:
        out.add(plain.rstrip("0").rstrip("."))
    return {v for v in out if v}


def main() -> int:
    EVAL.mkdir(parents=True, exist_ok=True)
    tex = sorted((PAPER / "sections").glob("*.tex")) + [PAPER / "main-elsevier.tex"]
    tex = [t for t in tex if t.exists()]
    if not tex:
        sys.exit("no LaTeX sources found under paper/")

    hay = load_haystacks()

    found = defaultdict(list)     # number -> [(file, artefact)]
    missing = defaultdict(list)   # number -> [file]
    for t in tex:
        text = t.read_text(encoding="utf-8", errors="replace")
        for m in NUM.finditer(text):
            tok = m.group(1).rstrip(".")
            if tok in ALLOWED:
                continue
            hits = [label for label, blob in hay.items()
                    if any(v in blob for v in variants(tok))]
            if hits:
                found[tok].append((t.name, hits[0]))
            else:
                missing[tok].append(t.name)

    pending = sum(len(re.findall(r"\\pending\{", t.read_text(encoding="utf-8",
                                                             errors="replace")))
                  for t in tex)

    L = []
    A = L.append
    A("# Numbers manifest\n")
    A("Generated by `scripts/95_numbers_manifest.py`. Every `\\num{}` value in "
      "the manuscript is checked against the generated artefacts under `eval/` "
      "and `derived/processed/`.\n")
    A(f"- numeric claims checked: **{len(found) + len(missing)}**")
    A(f"- traced to a generated artefact: **{len(found)}**")
    A(f"- **untraced: {len(missing)}**")
    A(f"- `\\pending{{}}` markers still in the text: **{pending}**\n")

    if missing:
        A("## Untraced numbers — resolve before submission\n")
        A("| value | appears in | action |")
        A("|---|---|---|")
        for tok in sorted(missing, key=lambda x: -len(x)):
            files = ", ".join(sorted(set(missing[tok])))
            A(f"| `{tok}` | {files} | trace to a script output, or add to "
              f"`ALLOWED` with a reason |")
        A("")

    A("## Traced numbers\n")
    A("| value | in manuscript | produced in |")
    A("|---|---|---|")
    for tok in sorted(found, key=lambda x: (len(x), x)):
        f0, a0 = found[tok][0]
        A(f"| `{tok}` | {f0} | `{a0}` |")
    A("")

    A("## How to re-derive everything\n")
    A("```bash")
    # One line, because there is one answer. This block used to list eleven
    # scripts by hand, six of which belonged to the retired single-basin survey
    # and now live in attic/ -- shipped, in the file whose job is to tell a
    # reader how to reproduce the numbers.
    A("python scripts/00_run_all.py --waterbase "
      "Data/waterbase/WISE6_AggregatedData-csv.zip")
    A("```")
    A("")
    A("`00_run_all.py` holds the order and runs the audit last; running the "
      "stages by hand is what produced a figure quoting one value while the "
      "table behind it held another.")
    A("")
    A("External responses (PubChem, CrossRef) and every comparison ontology are "
      "cached in `derived/interim/`, so the pipeline re-derives the same values "
      "offline after those services change.\n")

    text = "\n".join(L)
    (EVAL / "numbers_manifest.md").write_text(text, encoding="utf-8")
    print(text[:2200])
    print(f"\nwrote: {EVAL/'numbers_manifest.md'}")
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
