#!/usr/bin/env python3
"""
Detection-onset analysis — the core method.

IDEA
----
A non-detection is not missing data. It is an UPPER BOUND, and an upper bound is
exactly what a source-location argument needs:

    substance absent upstream (< LOD)  +  present downstream (>= LOQ)
        =>  a source lies within that reach,
            contributing a load of at least (C_down - LOD_up) * Q_down

So the 85% of records normally discarded as "zeros" carry half the signal. And
binary detection is far more robust than concentration values near the limit.

WHAT THIS SCRIPT GUARDS AGAINST
-------------------------------
The naive query `WHERE conc = 0` conflates four different facts, and getting
this wrong manufactures sources out of nothing:

  1. measured, genuinely absent
  2. measured, present but below LOD          <- these two are the real signal
  3. NEVER MEASURED (analyte absent from that campaign's panel)
  4. measured, value lost

Case 3 is the dangerous one: if an analyte is missing from the upstream
station's panel but present downstream, a naive comparison reports an onset
where there is only a change of analytical scope. Every candidate onset here is
therefore required to have an ACTUAL OBSERVATION at both ends.

DILUTION TEST
-------------
An onset is only informative if dilution cannot explain the upstream absence.
Where flow is available at both ends we require:

    C_down * Q_down  >  LOD_up * Q_up          (mass could not have come from upstream)

Without LOD the test cannot be run, so the reach-substance is reported as
UNDECIDABLE rather than as an onset. That distinction is the paper's point.

Inputs  (generated by scripts 01-04):
    derived/processed/{measurements,analytes,stations_snapped,reaches}.csv
Outputs:
    derived/processed/onsets.csv
    derived/processed/reach_onset_summary.csv
    eval/detection_onset.md

Usage:  python scripts/05_detection_onset.py [--all-pairs]
"""

from __future__ import annotations

import argparse
import csv
import sys
import unicodedata
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROC = ROOT / "derived" / "processed"
EVAL = ROOT / "eval"

# Flow series. Matched case- and diacritic-insensitively: the source sheets spell
# the provider name inconsistently ("Yabatas" / "Yabataş"), and an exact string
# constant silently produced zero matches on the first run.
FLOW_PARAMS = ("yabatas", "ekoton")   # m3/s; preference order
PRIMARY_FLOW = "yabatas"
CAMPAIGN_ORDER = ["C1", "C2", "C3", "C4"]
CAMPAIGN_LABEL = {"C1": "Aug-2017", "C2": "Nov-2017",
                  "C3": "Feb-2018", "C4": "May-2018"}


def fold(text: str) -> str:
    """Case- and diacritic-insensitive key for matching parameter names."""
    t = text.replace("ı", "i").replace("İ", "i").replace("ş", "s").replace("Ş", "s")
    t = t.replace("ğ", "g").replace("Ğ", "g").replace("ç", "c").replace("Ç", "c")
    t = t.replace("ö", "o").replace("Ö", "o").replace("ü", "u").replace("Ü", "u")
    t = unicodedata.normalize("NFKD", t)
    return "".join(c for c in t if not unicodedata.combining(c)).strip().lower()


def load(name):
    p = PROC / name
    if not p.exists():
        sys.exit(f"missing {p}; run the earlier scripts first")
    return list(csv.DictReader(p.open(encoding="utf-8")))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--all-pairs", action="store_true",
                    help="use every ordered station pair, not only immediate reaches")
    args = ap.parse_args()
    EVAL.mkdir(parents=True, exist_ok=True)

    measurements = load("measurements.csv")
    analytes = {a["parameter"]: a for a in load("analytes.csv")}
    reaches = load("reaches.csv")

    # ---- index: (campaign, station, parameter) -> observation ----
    # Presence of a key means an observation EXISTS. Absence means the analyte
    # was not measured there -- case 3 above -- and must never be read as zero.
    obs = {}
    flow_by_series = {k: {} for k in FLOW_PARAMS}
    for m in measurements:
        key = (m["campaign"], m["station"], m["parameter"])
        val = None if m["value_num"] == "" else float(m["value_num"])
        obs[key] = val
        f = fold(m["parameter"])
        if f in flow_by_series and val is not None and val > 0:
            flow_by_series[f][(m["campaign"], m["station"])] = val

    # Prefer the primary series; fall back to the secondary where it is missing.
    flow = dict(flow_by_series[PRIMARY_FLOW])
    n_primary = len(flow)
    for k, v in flow_by_series.items():
        if k == PRIMARY_FLOW:
            continue
        for kk, vv in v.items():
            flow.setdefault(kk, vv)
    if not flow:
        sys.exit("no flow data matched; check FLOW_PARAMS against parameters.csv")
    print(f"flow: {n_primary} from '{PRIMARY_FLOW}', {len(flow)-n_primary} from "
          f"fallback series, {len(flow)} total station-campaigns\n")

    # ---- which analytes can carry a dilution test? ----
    lod = {}
    for p, a in analytes.items():
        if a["lod"] not in ("", None):
            try:
                lod[p] = float(a["lod"])
            except ValueError:
                pass

    chem = [p for p, a in analytes.items()
            if a["group"] in ("micropollutant", "metal", "conventional")]

    selected = reaches if args.all_pairs else [r for r in reaches
                                               if r["immediate"] == "True"]
    if not selected:
        sys.exit("no reaches selected")

    # ---- classify every reach x analyte x campaign ----
    rows = []
    tally = defaultdict(int)
    for r in selected:
        u, d = r["up_station"], r["down_station"]
        for camp in CAMPAIGN_ORDER:
            qu = flow.get((camp, u))
            qd = flow.get((camp, d))
            for p in chem:
                ku, kd = (camp, u, p), (camp, d, p)
                # ---- guard: both ends must actually have been observed ----
                if ku not in obs or kd not in obs:
                    tally["not_measured_both_ends"] += 1
                    continue
                vu, vd = obs[ku], obs[kd]
                if vu is None or vd is None:
                    tally["value_missing"] += 1
                    continue

                up_detect = vu > 0
                down_detect = vd > 0

                if up_detect and down_detect:
                    verdict = "present_both"
                elif up_detect and not down_detect:
                    verdict = "disappearance"
                elif not up_detect and not down_detect:
                    verdict = "absent_both"
                else:
                    # candidate onset: absent upstream, present downstream
                    if p not in lod:
                        verdict = "onset_undecidable_no_lod"
                    elif qu is None or qd is None:
                        verdict = "onset_undecidable_no_flow"
                    else:
                        # Could the downstream mass have come from upstream,
                        # given that upstream was below its detection limit?
                        max_up_load = lod[p] * qu
                        down_load = vd * qd
                        verdict = ("onset_confirmed" if down_load > max_up_load
                                   else "onset_possible")
                tally[verdict] += 1

                if verdict.startswith("onset"):
                    rows.append({
                        "reach_id": r["reach_id"], "up_station": u,
                        "down_station": d, "campaign": camp,
                        "campaign_label": CAMPAIGN_LABEL[camp],
                        "analyte": p, "group": analytes[p]["group"],
                        "up_value": vu, "down_value": vd,
                        "lod": lod.get(p, ""),
                        "q_up": qu if qu is not None else "",
                        "q_down": qd if qd is not None else "",
                        "down_load": (vd * qd) if qd is not None else "",
                        "max_upstream_load": (lod[p] * qu)
                                             if (p in lod and qu is not None) else "",
                        "verdict": verdict,
                    })

    with (PROC / "onsets.csv").open("w", newline="", encoding="utf-8") as fh:
        if rows:
            w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
            w.writeheader()
            w.writerows(sorted(rows, key=lambda x: (x["reach_id"], x["analyte"],
                                                    x["campaign"])))

    # ---- seasonal persistence per (reach, analyte) ----
    persist = defaultdict(set)
    for x in rows:
        if x["verdict"] in ("onset_confirmed", "onset_possible"):
            persist[(x["reach_id"], x["analyte"])].add(x["campaign"])

    per_reach = defaultdict(lambda: defaultdict(int))
    for (rid, p), camps in persist.items():
        per_reach[rid]["analytes"] += 1
        per_reach[rid][f"persist_{len(camps)}"] += 1
        if len(camps) >= 3:
            per_reach[rid]["persistent"] += 1

    with (PROC / "reach_onset_summary.csv").open("w", newline="",
                                                 encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["reach_id", "up_station", "down_station", "n_analyte_onsets",
                    "n_persistent_ge3", "persist_1", "persist_2", "persist_3",
                    "persist_4"])
        for r in selected:
            rid = r["reach_id"]
            s = per_reach.get(rid, {})
            w.writerow([rid, r["up_station"], r["down_station"],
                        s.get("analytes", 0), s.get("persistent", 0),
                        s.get("persist_1", 0), s.get("persist_2", 0),
                        s.get("persist_3", 0), s.get("persist_4", 0)])

    # ---- report ----
    total = sum(tally.values())
    onset_conf = tally["onset_confirmed"]
    onset_poss = tally["onset_possible"]
    onset_und = tally["onset_undecidable_no_lod"] + tally["onset_undecidable_no_flow"]
    onset_all = onset_conf + onset_poss + onset_und

    L = []
    A = L.append
    A("# Detection-onset analysis\n")
    A("Generated by `scripts/05_detection_onset.py`.\n")
    A(f"Reaches used: **{len(selected)}** "
      f"({'all ordered station pairs' if args.all_pairs else 'immediate reaches only'}) "
      f"x {len(chem)} chemical analytes x {len(CAMPAIGN_ORDER)} campaigns.\n")

    A("## Outcome of every reach x analyte x campaign comparison\n")
    A("| outcome | n | share |")
    A("|---|---|---|")
    for k in ["absent_both", "present_both", "disappearance", "onset_confirmed",
              "onset_possible", "onset_undecidable_no_lod",
              "onset_undecidable_no_flow", "not_measured_both_ends",
              "value_missing"]:
        if tally[k]:
            A(f"| `{k}` | {tally[k]:,} | {100*tally[k]/total:.2f}% |")
    A(f"| **total** | **{total:,}** | |")
    A("")

    A("## Onsets\n")
    A(f"- Candidate onsets (absent upstream, present downstream): **{onset_all:,}**")
    A(f"  - **confirmed** — downstream load exceeds the maximum the upstream "
      f"non-detection permits: **{onset_conf:,}**")
    A(f"  - **possible** — dilution could still explain it: **{onset_poss:,}**")
    A(f"  - **undecidable** — no LOD ({tally['onset_undecidable_no_lod']:,}) "
      f"or no flow ({tally['onset_undecidable_no_flow']:,}): **{onset_und:,}**")
    A("")
    if onset_all:
        A(f"> {100*onset_und/onset_all:.1f}% of candidate onsets cannot be decided, "
          f"almost entirely because the analyte has no published detection limit. "
          f"Reporting these as findings would be unfounded; discarding them "
          f"silently would hide the gap. They are returned as an explicit "
          f"`UndecidableReach` verdict.\n")

    # ---- top reaches ----
    ranked = sorted(per_reach.items(),
                    key=lambda kv: -kv[1].get("persistent", 0))[:15]
    if ranked:
        A("## Reaches ranked by persistent onsets\n")
        A("A source that is real should show up across campaigns; a one-off is "
          "either intermittent or an artefact. `persistent` counts analytes with "
          "an onset in at least 3 of the 4 campaigns.\n")
        A("| reach | analytes with onset | persistent (>=3 campaigns) |")
        A("|---|---|---|")
        for rid, s in ranked:
            A(f"| {rid} | {s.get('analytes',0)} | {s.get('persistent',0)} |")
        A("")

    # ---- most frequently onsetting substances ----
    by_analyte = defaultdict(int)
    for (rid, p), camps in persist.items():
        if len(camps) >= 3:
            by_analyte[p] += 1
    if by_analyte:
        A("## Substances with persistent onsets in the most reaches\n")
        A("| analyte | group | reaches |")
        A("|---|---|---|")
        for p, n in sorted(by_analyte.items(), key=lambda x: -x[1])[:20]:
            A(f"| {p} | {analytes[p]['group']} | {n} |")
        A("")

    A("## Interpretation guard\n")
    A("An onset localises where a substance *first appears*, not who emitted it. "
      "Attribution to a source type requires the substance-to-use-class mapping, "
      "which must come from an external citable source rather than from the "
      "analyst, or the land-use validation becomes circular.\n")

    text = "\n".join(L)
    (EVAL / "detection_onset.md").write_text(text, encoding="utf-8")
    print(text)
    print(f"\nwrote: {EVAL/'detection_onset.md'}, {PROC/'onsets.csv'}, "
          f"{PROC/'reach_onset_summary.csv'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
